import { MigrationInterface, QueryRunner } from 'typeorm';

// Several datasets per instance (issue #527). The registry and the active
// dataset live in `public`; the dictionary tables that exist here become the
// `default` dataset without moving. `public` is registered as a dataset
// schema by marking the dataset baseline as applied — its tables were built
// by the migrations before this one. The audit journal learns which dataset
// a row is about: entity ids are per dataset from here on.
const DEFAULT_ATTRIBUTION =
  'Vocabulary data from the Vocab Bloom Hub English dataset (CC BY 4.0), https://huggingface.co/datasets/Fristail27/vocab-bloom-hub-en';
const DEFAULT_NOTICE =
  'Generated by language models and not human-verified: definitions, examples, levels and translations may contain errors.';

export class AddDatasets1789600000000 implements MigrationInterface {
  name = 'AddDatasets1789600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "public"."datasets" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(40) NOT NULL, "schema" character varying(63) NOT NULL, "source" character varying(64) NOT NULL, "language" character varying(8) NOT NULL DEFAULT 'en', "version" character varying(64), "license" character varying(64) NOT NULL, "license_url" text NOT NULL, "attribution" text NOT NULL, "attribution_url" text, "notice" text, "imported_at" TIMESTAMP WITH TIME ZONE, "activated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_datasets_name" UNIQUE ("name"), CONSTRAINT "UQ_datasets_schema" UNIQUE ("schema"), CONSTRAINT "PK_datasets" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `INSERT INTO "public"."datasets" ("name", "schema", "source", "language", "version", "license", "license_url", "attribution", "attribution_url", "notice")
       VALUES ('default', 'public', 'vocab-bloom-hub', 'en',
               (SELECT "value" FROM "public"."settings" WHERE "field" = 'en_dataset_version'),
               'CC-BY-4.0', 'https://creativecommons.org/licenses/by/4.0/', $1,
               'https://huggingface.co/datasets/Fristail27/vocab-bloom-hub-en', $2)`,
      [DEFAULT_ATTRIBUTION, DEFAULT_NOTICE],
    );
    await queryRunner.query(
      `INSERT INTO "public"."settings" ("field", "value") VALUES ('active_dataset', 'default') ON CONFLICT ("field") DO NOTHING`,
    );

    await queryRunner.query(
      `CREATE TABLE IF NOT EXISTS "public"."dataset_migrations" ("id" SERIAL NOT NULL, "timestamp" bigint NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_dataset_migrations" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `INSERT INTO "public"."dataset_migrations" ("timestamp", "name") VALUES (1789500000000, 'DatasetBaseline1789500000000')`,
    );

    await queryRunner.query(`ALTER TABLE "public"."audit_log" ADD "dataset" character varying(40)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "public"."audit_log" DROP COLUMN "dataset"`);
    await queryRunner.query(`DROP TABLE "public"."dataset_migrations"`);
    await queryRunner.query(`DELETE FROM "public"."settings" WHERE "field" = 'active_dataset'`);
    await queryRunner.query(`DROP TABLE "public"."datasets"`);
  }
}
